/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.administrasi;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import Control.Agama;
import Control.Status;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.text.DateFormat;
import java.util.HashMap;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
import sun.audio.*;

/**
 *
 * @author ASUS R.O.G
 */
public class Home extends javax.swing.JFrame {
    private Connection konek;
    private Statement stat;
    private ResultSet rs;
    private ButtonModel rbPria;
    private ButtonModel rbPerempuan;
    
    /**
     * Creates new form Home
     */
    
    public Home() {
        initComponents();
        updateTabel("");
        rbJenisKelaminGroup.add(inputJK1);
        rbJenisKelaminGroup.add(inputJK2);
        this.rbPria = inputJK1.getModel();
        this.rbPerempuan = inputJK2.getModel();
        statusBar();
    }
    
    private void statusBar(){
        //Three panels that are to added to the JFrame
        JPanel statusBar = new JPanel();
        JLabel welcomedate;
 
        //Creating the StatusBar.
        setLayout(new BorderLayout());//frame layout
        welcomedate = new JLabel();
        welcomedate.setOpaque(true);//to set the color for jlabel
        welcomedate.setBackground(Color.black);
        welcomedate.setForeground(Color.WHITE);
        statusBar.setLayout(new BorderLayout());
        statusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusBar.setBackground(Color.LIGHT_GRAY);
        statusBar.add(welcomedate, BorderLayout.EAST);
        add("South", statusBar);
        //display date time to status bar
        Timer timee = new Timer(1000, (ActionEvent e) -> {
            java.util.Date now = new java.util.Date();
            String ss = DateFormat.getDateTimeInstance().format(now);
            welcomedate.setText(ss);
            welcomedate.setToolTipText("Welcome, Today is " + ss);
        });
        timee.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbJenisKelaminGroup = new javax.swing.ButtonGroup();
        formData = new javax.swing.JPanel();
        labelEmail = new javax.swing.JLabel();
        labelNamaDepan = new javax.swing.JLabel();
        labelJenisKelamin = new javax.swing.JLabel();
        labelAgama = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        inputNRA = new javax.swing.JTextField();
        inputNamaLengkap = new javax.swing.JTextField();
        cbAgama = new javax.swing.JComboBox<>();
        cbStatus = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        inputJK1 = new javax.swing.JRadioButton();
        inputJK2 = new javax.swing.JRadioButton();
        btnDataBaru = new javax.swing.JButton();
        btnHapusData = new javax.swing.JButton();
        btnUpdateData = new javax.swing.JButton();
        refreshButton = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelData = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        printKTA = new javax.swing.JButton();
        nraPrint = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARSIP DATA MAHASISWA");
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1155, 625));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        formData.setBackground(new java.awt.Color(250, 250, 250));
        formData.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEmail.setBackground(new java.awt.Color(39, 129, 191));
        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelEmail.setForeground(new java.awt.Color(39, 129, 191));
        labelEmail.setText("NRA");
        formData.add(labelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 77, 55, 35));

        labelNamaDepan.setBackground(new java.awt.Color(39, 129, 191));
        labelNamaDepan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelNamaDepan.setForeground(new java.awt.Color(39, 129, 191));
        labelNamaDepan.setText("Nama Lengkap");
        formData.add(labelNamaDepan, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 132, -1, 30));

        labelJenisKelamin.setBackground(new java.awt.Color(39, 129, 191));
        labelJenisKelamin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelJenisKelamin.setForeground(new java.awt.Color(39, 129, 191));
        labelJenisKelamin.setText("Jenis Kelamin");
        formData.add(labelJenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 29));

        labelAgama.setBackground(new java.awt.Color(39, 129, 191));
        labelAgama.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelAgama.setForeground(new java.awt.Color(39, 129, 191));
        labelAgama.setText("Agama");
        formData.add(labelAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, 30));

        labelStatus.setBackground(new java.awt.Color(39, 129, 191));
        labelStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(39, 129, 191));
        labelStatus.setText("Status");
        formData.add(labelStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 62, 30));

        inputNRA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        inputNRA.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputNRACaretUpdate(evt);
            }
        });
        formData.add(inputNRA, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 77, 275, 35));

        inputNamaLengkap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        formData.add(inputNamaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 130, 275, 35));

        cbAgama.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbAgama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Agama", "Islam", "Hindu", "Budha", "Kristen", "Katolik" }));
        formData.add(cbAgama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 275, 34));

        cbStatus.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status", "Menikah", "Belum Menikah" }));
        formData.add(cbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 275, 30));

        jLabel2.setBackground(new java.awt.Color(39, 129, 191));
        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 129, 191));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("biodata anggota");
        formData.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 13, 240, 46));

        inputJK1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        inputJK1.setText("Laki-Laki");
        inputJK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJK1ActionPerformed(evt);
            }
        });
        formData.add(inputJK1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        inputJK2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        inputJK2.setText("Perempuan");
        inputJK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJK2ActionPerformed(evt);
            }
        });
        formData.add(inputJK2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        btnDataBaru.setBackground(new java.awt.Color(9, 90, 146));
        btnDataBaru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDataBaru.setForeground(new java.awt.Color(255, 255, 255));
        btnDataBaru.setText("Tambah Data");
        btnDataBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataBaruActionPerformed(evt);
            }
        });
        formData.add(btnDataBaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 40));

        btnHapusData.setBackground(new java.awt.Color(9, 90, 146));
        btnHapusData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHapusData.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusData.setText("Hapus Data");
        btnHapusData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusDataActionPerformed(evt);
            }
        });
        formData.add(btnHapusData, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, 40));

        btnUpdateData.setBackground(new java.awt.Color(9, 90, 146));
        btnUpdateData.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnUpdateData.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateData.setText("Update Data");
        btnUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDataActionPerformed(evt);
            }
        });
        formData.add(btnUpdateData, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, -1, 40));

        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/refresh-35.png"))); // NOI18N
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshButtonMouseClicked(evt);
            }
        });
        formData.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 35, 35));

        getContentPane().add(formData);
        formData.setBounds(10, 50, 450, 430);

        tabelData.setFont(new java.awt.Font("Bebas Neue", 0, 20));
        JTableHeader header = tabelData.getTableHeader();
        header.setFont(new java.awt.Font("Bebas Neue", 0, 22));
        tabelData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NRA", "Nama Lengkap"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelData.setRowHeight(15);
        tabelData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelDataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelData);
        if (tabelData.getColumnModel().getColumnCount() > 0) {
            tabelData.getColumnModel().getColumn(0).setResizable(false);
            tabelData.getColumnModel().getColumn(1).setResizable(false);
        }
        tabelData.setAutoResizeMode(tabelData.AUTO_RESIZE_OFF);
        tabelData.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelData.getColumnModel().getColumn(1).setPreferredWidth(257);
        tabelData.setRowHeight(40);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(480, 50, 360, 430);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Bebas Neue", 0, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(39, 129, 191));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kartu Tanda Anggota");
        jLabel1.setPreferredSize(new java.awt.Dimension(40, 15));

        printKTA.setBackground(new java.awt.Color(9, 90, 146));
        printKTA.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        printKTA.setForeground(new java.awt.Color(255, 255, 255));
        printKTA.setText("Cetak KTA");
        printKTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printKTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(nraPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(printKTA)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(printKTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nraPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(860, 50, 250, 150);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void eksekusiUpdateSQL(String sql){
        try {
            konek = new Koneksi().koneksi();
            stat = konek.createStatement();
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null,"Proses berhasil");
            this.updateTabel("");
            konek.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Proses gagal");
            
        }
    }
    
    private void eksekusiAmbilSQL(String sql){
        try {
            konek = new Koneksi().koneksi();
            stat = konek.createStatement();
            rs = stat.executeQuery(sql);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    
    private void updateTabel(String sql){
        //membersihkan data tabel
        DefaultTableModel model = (DefaultTableModel) tabelData.getModel();
        model.setRowCount(0);
        
        //membuat data tabel
        if (sql.isEmpty()) {
            sql = "SELECT * FROM akun";
        }
        String nra, namaLengkap, jenisKelamin, agama, status;
        this.eksekusiAmbilSQL(sql);
        
        int id = 0;
        try {
            while(rs.next()){
                Object[] rowData = null;
                ((DefaultTableModel) tabelData.getModel()).addRow(rowData);
                
                //mengambil data dari database
                nra = rs.getString("NRA");
                namaLengkap = rs.getString("nama-lengkap");
                jenisKelamin = rs.getString("jenis-kelamin");
                agama = rs.getString("agama");
                status = rs.getString("status");
                
                //set data pada tabel
                tabelData.setValueAt(nra, id, 0);
                tabelData.setValueAt(namaLengkap, id, 1);
            }
            konek.close();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void resetPanelInput(){
        inputNRA.setText("");
        inputNRA.setEditable(true);
        inputNamaLengkap.setText("");
        
        //input jenis kelamin
        rbJenisKelaminGroup.clearSelection();
        
        cbAgama.setSelectedIndex(0);
        cbStatus.setSelectedIndex(0);
    }
    
    private void falseEditForm(){
        inputNamaLengkap.setEditable(false);
        inputJK1.setEnabled(false);
        inputJK2.setEnabled(false);
        cbAgama.setEditable(false);
        cbStatus.setEditable(false);
    }
    
    private void trueEditForm(){
        inputNRA.setEditable(true);
        inputNamaLengkap.setEditable(true);
        inputJK1.setEnabled(true);
        inputJK2.setEnabled(true);
        cbAgama.setEditable(true);
        cbStatus.setEditable(true);
    }
    
    private void btnHapusDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusDataActionPerformed
        String nra = inputNRA.getText();
        String sql = "DELETE FROM akun WHERE nra='%s'";
        sql = String.format(sql, nra);
        
        //proses menghapus data di database
        this.eksekusiUpdateSQL(sql);
        
        //membersihkan panel input data
        this.resetPanelInput();
    }//GEN-LAST:event_btnHapusDataActionPerformed

    private void btnDataBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataBaruActionPerformed
        String nra, namaLengkap, jenisKelamin="", agama="", status="";
        
        nra = inputNRA.getText();
        namaLengkap = inputNamaLengkap.getText();
        
        if (rbPria.isSelected()) {
            jenisKelamin="Laki-Laki";
        }
        else if (rbPerempuan.isSelected()) {
            jenisKelamin="Perempuan";
        }
        
        agama = Agama.getAgama(cbAgama.getSelectedIndex());
        
        status = Status.getStatus(cbStatus.getSelectedIndex());
                
        String sql = "INSERT INTO akun VALUES (null,'%s', '%s', '%s', '%s', '%s', '%s', '%s')";
        sql = String.format(sql, nra, namaLengkap, jenisKelamin, agama, status);
        this.eksekusiUpdateSQL(sql);
        
        this.resetPanelInput();
    }//GEN-LAST:event_btnDataBaruActionPerformed

    private void btnUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDataActionPerformed
        String nra, namaLengkap="", jenisKelamin="", agama="", status="";
        //mengambil data baru
        nra = inputNRA.getText();
        namaLengkap = inputNamaLengkap.getText();
        
        //jenis Kelamin
        if (rbPria.isSelected()) {
            jenisKelamin="Laki-Laki";
        }
        else if (rbPerempuan.isSelected()) {
            jenisKelamin="Perempuan";
        }

        agama = Agama.getAgama(cbAgama.getSelectedIndex());

        status = Status.getStatus(cbStatus.getSelectedIndex());
        
        String sql = "UPDATE `akun` SET `nama-depan`='%s',`nama-belakang`='%s',`umur`=%d,`jenis-kelamin`='%s',`agama`='%s',`status`='%s' WHERE `nra`='%s'";
        sql = String.format(sql, namaLengkap, jenisKelamin, agama, status, nra);
        this.eksekusiUpdateSQL(sql);
        
        //membersihkan panel input data
        this.resetPanelInput();
    }//GEN-LAST:event_btnUpdateDataActionPerformed

    private void inputJK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJK1ActionPerformed
        rbPria = rbJenisKelaminGroup.getSelection();
    }//GEN-LAST:event_inputJK1ActionPerformed

    private void inputJK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJK2ActionPerformed
        rbPerempuan = rbJenisKelaminGroup.getSelection();
    }//GEN-LAST:event_inputJK2ActionPerformed

    private void inputNRACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputNRACaretUpdate
        if (inputNRA.isEditable()) {
            String nra = inputNRA.getText();
            String sql = "SELECT * FROM akun WHERE `nra`='%s'";
            sql = String.format(sql, nra);
            eksekusiAmbilSQL(sql);
        
            try {
                if (rs.next()) {
                    trueEditForm();
                }else{
                    falseEditForm();
                }
            } catch (SQLException ex) {
                
            }
        }    
    }//GEN-LAST:event_inputNRACaretUpdate

    private void refreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshButtonMouseClicked
        // TODO add your handling code here:
        resetPanelInput();
        updateTabel("");
        trueEditForm();
    }//GEN-LAST:event_refreshButtonMouseClicked

    private void tabelDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelDataMouseClicked
        int baris = tabelData.getSelectedRow();
        String nra = tabelData.getModel().getValueAt(baris, 0).toString();
        updateForm(nra);
        nraPrint.setText(nra);
    }//GEN-LAST:event_tabelDataMouseClicked

    private void printKTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printKTAActionPerformed
        HashMap hash = new HashMap();
        Koneksi connect = new Koneksi();
        JasperDesign jd;
        JasperReport jr;
        JasperPrint jp;
        String nra = nraPrint.getText();
        try {
            String sql = "SELECT * FROM akun WHERE nra="+nra;
            jd = JRXmlLoader.load("./src/Report/kta.jrxml");
            JRDesignQuery newquery = new JRDesignQuery();
            newquery.setText(sql);
            jd.setQuery(newquery);
            jr = JasperCompileManager.compileReport(jd);
            jp = JasperFillManager.fillReport(jr, null, connect.conn);
            JasperViewer.viewReport(jp);
        } catch (JRException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printKTAActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        InputStream music;
        try {
            music = new FileInputStream(new File("src\\Sounds\\welcome.wav"));
            AudioStream as = new AudioStream(music);
            AudioPlayer.player.start(as);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened
    
    private void updateForm(String nra){
        String sql = "SELECT * FROM akun WHERE NRA='"+nra+"'";
        this.eksekusiAmbilSQL(sql);
        try {
            while(rs.next()){
                inputNRA.setText(rs.getString("NRA"));
                inputNamaLengkap.setText(rs.getString("nama-lengkap"));
                String jk = rs.getString("jenis-kelamin");
                if (jk.equals("Laki-Laki")) {
                    rbPria.setSelected(true);
                }else if (jk.equals("Perempuan")) {
                    rbPerempuan.setSelected(true);
                }
                int index = Agama.setAgama(rs.getString("agama"));
                cbAgama.setSelectedIndex(index);
                index = Status.setStatus(rs.getString("status"));
                cbStatus.setSelectedIndex(index);
            }
            konek.close();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDataBaru;
    private javax.swing.JButton btnHapusData;
    private javax.swing.JButton btnUpdateData;
    private javax.swing.JComboBox<String> cbAgama;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JPanel formData;
    private javax.swing.JRadioButton inputJK1;
    private javax.swing.JRadioButton inputJK2;
    private javax.swing.JTextField inputNRA;
    private javax.swing.JTextField inputNamaLengkap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgama;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelJenisKelamin;
    private javax.swing.JLabel labelNamaDepan;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel nraPrint;
    private javax.swing.JButton printKTA;
    private javax.swing.ButtonGroup rbJenisKelaminGroup;
    private javax.swing.JLabel refreshButton;
    private javax.swing.JTable tabelData;
    // End of variables declaration//GEN-END:variables
}
